/****************************************
 * [package=common]
 ****************************************/

[Prefix="physx::", NoDelete]
interface PxBase {
    void release();
    [Const] DOMString getConcreteTypeName();
    long getConcreteType();
    void setBaseFlag(PxBaseFlagEnum flag, boolean value);
    void setBaseFlags([Ref] PxBaseFlags inFlags);
    [Value] PxBaseFlags getBaseFlags();
    boolean isReleasable();
};

enum PxBaseFlagEnum {
    "PxBaseFlagEnum::eOWNS_MEMORY",
    "PxBaseFlagEnum::eIS_RELEASABLE"
};

[Prefix="physx::", StackAllocatable]
interface PxBaseFlags {
    void PxBaseFlags(unsigned short flags);
    boolean isSet(PxBaseFlagEnum flag);
    void raise(PxBaseFlagEnum flag);
    void clear(PxBaseFlagEnum flag);
};

[Prefix="physx::"]
interface PxBaseTask { };

[Prefix="physx::", StackAllocatable]
interface PxBoundedData {
    void PxBoundedData();
    attribute unsigned long count;
};
PxBoundedData implements PxStridedData;

[Prefix="physx::", StackAllocatable]
interface PxBounds3 {
    void PxBounds3();
    void PxBounds3([Const, Ref] PxVec3 minimum, [Const, Ref] PxVec3 maximum);
    void setEmpty();
    void setMaximal();
    void include([Const, Ref] PxVec3 v);
    boolean isEmpty();
    boolean intersects([Const, Ref] PxBounds3 b);
    boolean intersects1D([Const, Ref] PxBounds3 b, unsigned long axis);
    boolean contains([Const, Ref] PxVec3 v);
    boolean isInside([Const, Ref] PxBounds3 box);
    [Value] PxVec3 getCenter();
    [Value] PxVec3 getDimensions();
    [Value] PxVec3 getExtents();
    void scaleSafe(float scale);
    void scaleFast(float scale);
    void fattenSafe(float distance);
    void fattenFast(float distance);
    boolean isFinite();
    boolean isValid();
    [Value] attribute PxVec3 minimum;
    [Value] attribute PxVec3 maximum;
};

[Prefix="physx::", NoDelete]
interface PxCollection {
    void add([Ref] PxBase obj, optional unsigned long long id);
    void remove([Ref] PxBase obj);
    boolean contains([Ref] PxBase obj);
    void addId([Ref] PxBase obj, unsigned long long id);
    void removeId(unsigned long long id);
    //void add([Ref] PxCollection collection);      clashes with void add([Ref] PxBase object)
    //void remove([Ref] PxCollection collection);   clashes with void remove([Ref] PxBase object)
    unsigned long getNbObjects();
    [Ref] PxBase getObject(unsigned long index);
    PxBase find(unsigned long long id);
    unsigned long getNbIds();
    unsigned long long getId([Const, Ref] PxBase obj);
    void release();
};

[Prefix="physx::"]
interface PxCpuDispatcher { };

[Prefix="physx::"]
interface PxDefaultAllocator {
    void PxDefaultAllocator();
};

[Prefix="physx::"]
interface PxDefaultCpuDispatcher { };
PxDefaultCpuDispatcher implements PxCpuDispatcher;

[Prefix="physx::"]
interface PxDefaultErrorCallback {
    void PxDefaultErrorCallback();
};
PxDefaultErrorCallback implements PxErrorCallback;

[Prefix="physx::"]
interface PxErrorCallback {
    void reportError(PxErrorCodeEnum code, [Const] DOMString message, [Const] DOMString file, long line);
};

[JSImplementation="PxErrorCallback"]
interface PxErrorCallbackImpl {
    void PxErrorCallbackImpl();
    void reportError(PxErrorCodeEnum code, [Const] DOMString message, [Const] DOMString file, long line);
};

enum PxErrorCodeEnum {
    "PxErrorCodeEnum::eNO_ERROR",
    "PxErrorCodeEnum::eDEBUG_INFO",
    "PxErrorCodeEnum::eDEBUG_WARNING",
    "PxErrorCodeEnum::eINVALID_PARAMETER",
    "PxErrorCodeEnum::eINVALID_OPERATION",
    "PxErrorCodeEnum::eOUT_OF_MEMORY",
    "PxErrorCodeEnum::eINTERNAL_ERROR",
    "PxErrorCodeEnum::eABORT",
    "PxErrorCodeEnum::ePERF_WARNING",
    "PxErrorCodeEnum::eMASK_ALL"
};

[Prefix="physx::", NoDelete]
interface PxFoundation {
    void release();
};

enum PxIDENTITYEnum {
    "PxIDENTITYEnum::PxIdentity"
};

[Prefix="physx::"]
interface PxInputData { };

[Prefix="physx::", NoDelete]
interface PxInsertionCallback { };

[Prefix="physx::"]
interface PxMat33 {
    void PxMat33();
    void PxMat33(PxIDENTITYEnum r);
    void PxMat33([Const, Ref] PxVec3 col0, [Const, Ref] PxVec3 col1, [Const, Ref] PxVec3 col2);
    void PxMat33(float r);
    void PxMat33([Const, Ref] PxQuat q);

    [Value] PxMat33 getTranspose();
    [Value] PxMat33 getInverse();
    float getDeterminant();
    [Value] PxVec3 transform([Const, Ref] PxVec3 other);
    [Value] PxVec3 transformTranspose([Const, Ref] PxVec3 other);

    [Value] attribute PxVec3 column0;
    [Value] attribute PxVec3 column1;
    [Value] attribute PxVec3 column2;
};

[Prefix="physx::"]
interface PxOutputStream { };

[Prefix="physx::", StackAllocatable]
interface PxPlane {
    void PxPlane();
    void PxPlane(float nx, float ny, float nz, float distance);
    void PxPlane([Const, Ref] PxVec3 normal, float distance);
    void PxPlane([Const, Ref] PxVec3 point, [Const, Ref] PxVec3 normal);
    void PxPlane([Const, Ref] PxVec3 p0, [Const, Ref] PxVec3 p1, [Const, Ref] PxVec3 p2);
    float distance([Const, Ref] PxVec3 p);
    boolean contains([Const, Ref] PxVec3 p);
    [Value] PxVec3 project([Const, Ref] PxVec3 p);
    [Value] PxVec3 pointInPlane();
    void normalize();
    [Value] PxPlane transform([Const, Ref] PxTransform pose);
    [Value] PxPlane inverseTransform([Const, Ref] PxTransform pose);

    [Value] attribute PxVec3 n;
    attribute float d;
};

[Prefix="physx::", StackAllocatable]
interface PxQuat {
    void PxQuat();
    void PxQuat(PxIDENTITYEnum r);
    void PxQuat(float r);
    void PxQuat(float nx, float ny, float nz, float nw);
    void PxQuat(float angleRadians, [Const, Ref] PxVec3 unitAxis);
    void PxQuat([Const, Ref] PxMat33 m);

    boolean isIdentity();
    boolean isFinite();
    boolean isUnit();
    boolean isSane();
    float getAngle();
    float getAngle([Const, Ref] PxQuat q);
    float magnitudeSquared();
    float dot([Const, Ref] PxQuat q);
    [Value] PxQuat getNormalized();
    float magnitude();
    float normalize();
    [Value] PxQuat getConjugate();
    [Value] PxVec3 getImaginaryPart();
    [Value] PxVec3 getBasisVector0();
    [Value] PxVec3 getBasisVector1();
    [Value] PxVec3 getBasisVector2();
    [Value] PxVec3 rotate([Const, Ref] PxVec3 v);
    [Value] PxVec3 rotateInv([Const, Ref] PxVec3 v);

    attribute float x;
    attribute float y;
    attribute float z;
    attribute float w;
};

[Prefix="physx::", NoDelete]
interface PxRefCounted {
    unsigned long getReferenceCount();
    void acquireReference();
};
PxRefCounted implements PxBase;

[Prefix="physx::"]
interface PxStridedData {
    attribute unsigned long stride;
    [Const] attribute VoidPtr data;
};

[Prefix="physx::"]
interface PxTolerancesScale {
    void PxTolerancesScale();
    boolean isValid();

    [Value] attribute float length;
    [Value] attribute float speed;
};

[Prefix="physx::", StackAllocatable]
interface PxTransform {
    void PxTransform();
    void PxTransform([Const, Ref] PxVec3 position);
    void PxTransform(PxIDENTITYEnum r);
    void PxTransform([Const, Ref] PxVec3 p0, [Const, Ref] PxQuat q0);

    [Value] PxTransform getInverse();
    [Value] PxVec3 transform([Const, Ref] PxVec3 input);
    [Value] PxVec3 transformInv([Const, Ref] PxVec3 input);
    boolean isValid();
    boolean isSane();
    boolean isFinite();
    [Value] PxTransform getNormalized();

    [Value] attribute PxQuat q;
    [Value] attribute PxVec3 p;
};

interface PxU16StridedData {
    attribute unsigned long stride;
    [Const, Value] attribute PxU16ConstPtr data;
};

[Prefix="physx::", StackAllocatable]
interface PxVec3 {
    void PxVec3();
    void PxVec3(float x, float y, float z);

    boolean isZero();
    boolean isFinite();
    boolean isNormalized();
    float magnitudeSquared();
    float magnitude();
    float dot([Const, Ref] PxVec3 v);
    [Value] PxVec3 cross([Const, Ref] PxVec3 v);
    [Value] PxVec3 getNormalized();
    float normalize();
    float normalizeSafe();
    float normalizeFast();
    [Value] PxVec3 multiply([Const, Ref] PxVec3 a);
    [Value] PxVec3 minimum([Const, Ref] PxVec3 v);
    float minElement();
    [Value] PxVec3 maximum([Const, Ref] PxVec3 v);
    float maxElement();
    [Value] PxVec3 abs();

    attribute float x;
    attribute float y;
    attribute float z;
};

[Prefix="physx::", StackAllocatable]
interface PxVec4 {
    void PxVec4();
    void PxVec4(float x, float y, float z, float w);

    boolean isZero();
    boolean isFinite();
    boolean isNormalized();
    float magnitudeSquared();
    float magnitude();
    float dot([Const, Ref] PxVec4 v);
    [Value] PxVec4 getNormalized();
    float normalize();
    [Value] PxVec4 multiply([Const, Ref] PxVec4 a);
    [Value] PxVec4 minimum([Const, Ref] PxVec4 v);
    [Value] PxVec4 maximum([Const, Ref] PxVec4 v);
    [Value] PxVec3 getXYZ();

    attribute float  x;
    attribute float y;
    attribute float z;
    attribute float w;
};