/****************************************
 * [package=support]
 ****************************************/

interface SupportFunctions {
    static PxShape PxActor_getShape([Ref] PxRigidActor actor, long index);
    [Ref] static PxArray_PxActorPtr PxScene_getActiveActors(PxScene scene);
    static unsigned long PxArticulationReducedCoordinate_getMinSolverPositionIterations(PxArticulationReducedCoordinate articulation);
    static unsigned long PxArticulationReducedCoordinate_getMinSolverVelocityIterations(PxArticulationReducedCoordinate articulation);
};

interface PxU8Ptr { };
PxU8Ptr implements PxU8ConstPtr;

interface PxU8ConstPtr { };

interface PxU16Ptr { };
PxU16Ptr implements PxU16ConstPtr;

interface PxU16ConstPtr { };

interface PxU32Ptr { };
PxU32Ptr implements PxU32ConstPtr;

interface PxU32ConstPtr { };

interface PxI32Ptr { };
PxI32Ptr implements PxI32ConstPtr;

interface PxI32ConstPtr { };

interface PxRealPtr { };
PxRealPtr implements PxRealConstPtr;

interface PxRealConstPtr { };

interface PxActorPtr { };

interface PxMaterialPtr { };

interface PxMaterialConstPtr { };

interface PxVehicleWheelsPtr { };

interface PxShapePtr { };

interface NativeArrayHelpers {
    static octet getU8At([Ref] PxU8ConstPtr base, long index);
    static unsigned short getU16At([Ref] PxU16ConstPtr base, long index);
    static unsigned long getU32At([Ref] PxU32ConstPtr base, long index);
    static float getRealAt([Ref] PxRealPtr base, long index);

    static void setU8At(VoidPtr base, long index, octet value);
    static void setU16At(VoidPtr base, long index, unsigned short value);
    static void setU32At(VoidPtr base, long index, unsigned long value);
    static void setRealAt(VoidPtr base, long index, float value);

    [Value] static PxU8Ptr voidToU8Ptr(VoidPtr voidPtr);
    [Value] static PxU16Ptr voidToU16Ptr(VoidPtr voidPtr);
    [Value] static PxU32Ptr voidToU32Ptr(VoidPtr voidPtr);
    [Value] static PxI32Ptr voidToI32Ptr(VoidPtr voidPtr);
    [Value] static PxRealPtr voidToRealPtr(VoidPtr voidPtr);

    static PxActor getActorAt(PxActor base, long index);
    static PxBounds3 getBounds3At(PxBounds3 base, long index);
    static PxContactPair getContactPairAt(PxContactPair base, long index);
    static PxContactPairHeader getContactPairHeaderAt(PxContactPairHeader base, long index);
    static PxController getControllerAt(PxController base, long index);
    static PxControllerShapeHit getControllerShapeHitAt(PxControllerShapeHit base, long index);
    static PxControllersHit getControllersHitAt(PxControllersHit base, long index);
    static PxControllerObstacleHit getControllerObstacleHitAt(PxControllerObstacleHit base, long index);
    static PxDebugPoint getDebugPointAt(PxDebugPoint base, long index);
    static PxDebugLine getDebugLineAt(PxDebugLine base, long index);
    static PxDebugTriangle getDebugTriangleAt(PxDebugTriangle base, long index);
    static PxObstacle getObstacleAt(PxObstacle base, long index);
    static PxShape getShapeAt(PxShape base, long index);
    static PxTriggerPair getTriggerPairAt(PxTriggerPair base, long index);
    static PxVec3 getVec3At(PxVec3 base, long index);
};

[StackAllocatable]
interface PxArray_PxMaterialConst {
    void PxArray_PxMaterialConst();
    void PxArray_PxMaterialConst(unsigned long size);
    [Const] PxMaterial get(unsigned long index);
    void set(unsigned long index, [Const, Ref] PxMaterialConstPtr value);
    PxMaterialConstPtr begin();
    unsigned long size();
    void pushBack([Const] PxMaterial value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxHeightFieldSample {
    void PxArray_PxHeightFieldSample();
    void PxArray_PxHeightFieldSample(unsigned long size);
    [Ref] PxHeightFieldSample get(unsigned long index);
    void set(unsigned long index, [Const, Ref] PxHeightFieldSample value);
    PxHeightFieldSample begin();
    unsigned long size();
    void pushBack([Ref] PxHeightFieldSample value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxReal {
    void PxArray_PxReal();
    void PxArray_PxReal(unsigned long size);
    float get(unsigned long index);
    void set(unsigned long index, float value);
    VoidPtr begin();
    unsigned long size();
    void pushBack(float value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxU8 {
    void PxArray_PxU8();
    void PxArray_PxU8(unsigned long size);
    octet get(unsigned long index);
    void set(unsigned long index, octet value);
    VoidPtr begin();
    unsigned long size();
    void pushBack(octet value);
    void setFromBuffer(VoidPtr buffer, unsigned long size);
    void clear();
};

[StackAllocatable]
interface PxArray_PxU16 {
    void PxArray_PxU16();
    void PxArray_PxU16(unsigned long size);
    unsigned short get(unsigned long index);
    void set(unsigned long index, unsigned short value);
    VoidPtr begin();
    unsigned long size();
    void pushBack(unsigned short value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxU32 {
    void PxArray_PxU32();
    void PxArray_PxU32(unsigned long size);
    unsigned long get(unsigned long index);
    void set(unsigned long index, unsigned long value);
    VoidPtr begin();
    unsigned long size();
    void pushBack(unsigned long value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxVec3 {
    void PxArray_PxVec3();
    void PxArray_PxVec3(unsigned long size);
    [Ref] PxVec3 get(unsigned long index);
    void set(unsigned long index, [Const, Ref] PxVec3 value);
    PxVec3 begin();
    unsigned long size();
    void pushBack([Ref] PxVec3 value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxVec4 {
    void PxArray_PxVec4();
    void PxArray_PxVec4(unsigned long size);
    [Ref] PxVec4 get(unsigned long index);
    void set(unsigned long index, [Const, Ref] PxVec4 value);
    PxVec4 begin();
    unsigned long size();
    void pushBack([Ref] PxVec4 value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxActorPtr {
    void PxArray_PxActorPtr();
    void PxArray_PxActorPtr(unsigned long size);
    PxActor get(unsigned long index);
    void set(unsigned long index, [Const, Ref] PxActorPtr value);
    PxActorPtr begin();
    unsigned long size();
    void pushBack(PxActor value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxContactPairPoint {
    void PxArray_PxContactPairPoint();
    void PxArray_PxContactPairPoint(unsigned long size);
    [Ref] PxContactPairPoint get(unsigned long index);
    void set(unsigned long index, [Const, Ref] PxContactPairPoint value);
    PxContactPairPoint begin();
    unsigned long size();
    void pushBack([Ref] PxContactPairPoint value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxRaycastHit {
    void PxArray_PxRaycastHit();
    void PxArray_PxRaycastHit(unsigned long size);
    [Ref] PxRaycastHit get(unsigned long index);
    void set(unsigned long index, [Const, Ref] PxRaycastHit value);
    PxRaycastHit begin();
    unsigned long size();
    void pushBack([Ref] PxRaycastHit value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxSweepHit {
    void PxArray_PxSweepHit();
    void PxArray_PxSweepHit(unsigned long size);
    [Ref] PxSweepHit get(unsigned long index);
    void set(unsigned long index, [Const, Ref] PxSweepHit value);
    PxSweepHit begin();
    unsigned long size();
    void pushBack([Ref] PxSweepHit value);
    void clear();
};

[Deprecated]
interface Vector_PxMaterialConst {
    void Vector_PxMaterialConst();
    void Vector_PxMaterialConst(unsigned long size);
    [Const] PxMaterial at(unsigned long index);
    PxMaterialConstPtr data();
    unsigned long size();
    void push_back([Const] PxMaterial value);
    void clear();
};

[Deprecated]
interface Vector_PxHeightFieldSample {
    void Vector_PxHeightFieldSample();
    void Vector_PxHeightFieldSample(unsigned long size);
    [Ref] PxHeightFieldSample at(unsigned long index);
    PxHeightFieldSample data();
    unsigned long size();
    void push_back([Ref] PxHeightFieldSample value);
    void clear();
};

[StackAllocatable]
interface PxArray_PxShapePtr {
    void PxArray_PxShapePtr();
    void PxArray_PxShapePtr(unsigned long size);
    PxShape get(unsigned long index);
    void set(unsigned long index, [Const, Ref] PxShapePtr value);
    PxShapePtr begin();
    unsigned long size();
    void pushBack(PxShape value);
    void clear();
};

[Deprecated]
interface Vector_PxReal {
    void Vector_PxReal();
    void Vector_PxReal(unsigned long size);
    float at(unsigned long index);
    VoidPtr data();
    unsigned long size();
    void push_back(float value);
    void clear();
};

[Deprecated]
interface Vector_PxU8 {
    void Vector_PxU8();
    void Vector_PxU8(unsigned long size);
    octet at(unsigned long index);
    VoidPtr data();
    unsigned long size();
    void push_back(octet value);
    void clear();
};

[Deprecated]
interface Vector_PxU16 {
    void Vector_PxU16();
    void Vector_PxU16(unsigned long size);
    unsigned short at(unsigned long index);
    VoidPtr data();
    unsigned long size();
    void push_back(unsigned short value);
    void clear();
};

[Deprecated]
interface Vector_PxU32 {
    void Vector_PxU32();
    void Vector_PxU32(unsigned long size);
    unsigned long at(unsigned long index);
    VoidPtr data();
    unsigned long size();
    void push_back(unsigned long value);
    void clear();
};

[Deprecated]
interface Vector_PxVec3 {
    void Vector_PxVec3();
    void Vector_PxVec3(unsigned long size);
    [Ref] PxVec3 at(unsigned long index);
    PxVec3 data();
    unsigned long size();
    void push_back([Ref] PxVec3 value);
    void clear();
};

[Deprecated]
interface Vector_PxVec4 {
    void Vector_PxVec4();
    void Vector_PxVec4(unsigned long size);
    [Ref] PxVec4 at(unsigned long index);
    PxVec4 data();
    unsigned long size();
    void push_back([Ref] PxVec4 value);
    void clear();
};

[Deprecated]
interface Vector_PxActorPtr {
    void Vector_PxActorPtr();
    void Vector_PxActorPtr(unsigned long size);
    PxActor at(unsigned long index);
    PxActorPtr data();
    unsigned long size();
    void push_back(PxActor value);
    void clear();
};

[Deprecated]
interface Vector_PxContactPairPoint {
    void Vector_PxContactPairPoint();
    void Vector_PxContactPairPoint(unsigned long size);
    [Ref] PxContactPairPoint at(unsigned long index);
    PxContactPairPoint data();
    unsigned long size();
    void push_back([Ref] PxContactPairPoint value);
    void clear();
};

[Deprecated]
interface Vector_PxRaycastHit {
    void Vector_PxRaycastHit();
    void Vector_PxRaycastHit(unsigned long size);
    [Ref] PxRaycastHit at(unsigned long index);
    PxRaycastHit data();
    unsigned long size();
    void push_back([Ref] PxRaycastHit value);
    void clear();
};

[Deprecated]
interface Vector_PxSweepHit {
    void Vector_PxSweepHit();
    void Vector_PxSweepHit(unsigned long size);
    [Ref] PxSweepHit at(unsigned long index);
    PxSweepHit data();
    unsigned long size();
    void push_back([Ref] PxSweepHit value);
    void clear();
};


interface PassThroughFilterShader {
    unsigned long filterShader(unsigned long attributes0,
                               unsigned long filterData0w0, unsigned long filterData0w1, unsigned long filterData0w2, unsigned long filterData0w3,
                               unsigned long attributes1,
                               unsigned long filterData1w0, unsigned long filterData1w1, unsigned long filterData1w2, unsigned long filterData1w3);

    attribute unsigned long outputPairFlags;
};
PassThroughFilterShader implements PxSimulationFilterShader;

[JSImplementation="PassThroughFilterShader"]
interface PassThroughFilterShaderImpl {
    void PassThroughFilterShaderImpl();
    unsigned long filterShader(unsigned long attributes0,
                               unsigned long filterData0w0, unsigned long filterData0w1, unsigned long filterData0w2, unsigned long filterData0w3,
                               unsigned long attributes1,
                               unsigned long filterData1w0, unsigned long filterData1w1, unsigned long filterData1w2, unsigned long filterData1w3);
};

enum PxVisualizationParameterEnum {
    "PxVisualizationParameterEnum::eSCALE",
    "PxVisualizationParameterEnum::eWORLD_AXES",
    "PxVisualizationParameterEnum::eBODY_AXES",
    "PxVisualizationParameterEnum::eBODY_MASS_AXES",
    "PxVisualizationParameterEnum::eBODY_LIN_VELOCITY",
    "PxVisualizationParameterEnum::eBODY_ANG_VELOCITY",
    "PxVisualizationParameterEnum::eCONTACT_POINT",
    "PxVisualizationParameterEnum::eCONTACT_NORMAL",
    "PxVisualizationParameterEnum::eCONTACT_ERROR",
    "PxVisualizationParameterEnum::eCONTACT_FORCE",
    "PxVisualizationParameterEnum::eACTOR_AXES",
    "PxVisualizationParameterEnum::eCOLLISION_AABBS",
    "PxVisualizationParameterEnum::eCOLLISION_SHAPES",
    "PxVisualizationParameterEnum::eCOLLISION_AXES",
    "PxVisualizationParameterEnum::eCOLLISION_COMPOUNDS",
    "PxVisualizationParameterEnum::eCOLLISION_FNORMALS",
    "PxVisualizationParameterEnum::eCOLLISION_EDGES",
    "PxVisualizationParameterEnum::eCOLLISION_STATIC",
    "PxVisualizationParameterEnum::eCOLLISION_DYNAMIC",
    "PxVisualizationParameterEnum::eJOINT_LOCAL_FRAMES",
    "PxVisualizationParameterEnum::eJOINT_LIMITS",
    "PxVisualizationParameterEnum::eCULL_BOX",
    "PxVisualizationParameterEnum::eMBP_REGIONS",
    "PxVisualizationParameterEnum::eSIMULATION_MESH",
    "PxVisualizationParameterEnum::eSDF",
    "PxVisualizationParameterEnum::eNUM_VALUES",
    "PxVisualizationParameterEnum::eFORCE_DWORD"
};

[Prefix="physx::", NoDelete]
interface PxPvd {
    boolean connect([Ref] PxPvdTransport transport, [Ref] PxPvdInstrumentationFlags flags);
    void release();
};

[Prefix="physx::", NoDelete]
interface PxPvdTransport {
    boolean connect();
    boolean isConnected();
    void disconnect();
    void release();
    void flush();
};

interface SimplePvdTransport {
    void send(any inBytes, unsigned long inLength);
};
SimplePvdTransport implements PxPvdTransport;

[JSImplementation="SimplePvdTransport"]
interface SimplPvdTransportImpl {
    void SimplPvdTransportImpl();
    boolean connect();
    boolean isConnected();
    void disconnect();
    void send(any inBytes, unsigned long inLength);
    void flush();
};

enum PxPvdInstrumentationFlagEnum {
    "PxPvdInstrumentationFlagEnum::eDEBUG",
    "PxPvdInstrumentationFlagEnum::ePROFILE",
    "PxPvdInstrumentationFlagEnum::eMEMORY",
    "PxPvdInstrumentationFlagEnum::eALL"
};

[Prefix="physx::"]
interface PxPvdInstrumentationFlags {
    void PxPvdInstrumentationFlags(octet flags);
    boolean isSet(PxPvdInstrumentationFlagEnum flag);
    void raise(PxPvdInstrumentationFlagEnum flag);
    void clear(PxPvdInstrumentationFlagEnum flag);
};

[Prefix="physx::"]
interface PxOmniPvd {
    [Platforms="windows;linux;macos"] OmniPvdWriter getWriter();
    [Platforms="windows;linux;macos"] OmniPvdFileWriteStream getFileWriteStream();
    boolean startSampling();
    void release();
};

[Platforms="windows;linux;macos"]
interface OmniPvdWriter {
    void setWriteStream([Ref] OmniPvdWriteStream writeStream);
};

[Platforms="windows;linux;macos", NoDelete]
interface OmniPvdFileWriteStream {
    void setFileName(DOMString fileName);
};
OmniPvdFileWriteStream implements OmniPvdWriteStream;

[Platforms="windows;linux;macos", NoDelete]
interface OmniPvdWriteStream { };